### ISSUE TITLE
Question about the tail re unit

### ISSUE THREAD

**Issue by debraj135** [Coopercoppers/PFN#8]
Is there a reason why the order of h_re and h_share are swapped [here ](https://github.com/Coopercoppers/PFN/blob/6173b3e6b048d1307766ee5d2f8178b30d6675b2/PFN-nested/model/pfn.py#L271) as compared to over [here](https://github.com/Coopercoppers/PFN/blob/6173b3e6b048d1307766ee5d2f8178b30d6675b2/PFN-nested/model/pfn.py#L269) ?

Thanks for any help.

**Comment by Coopercoppers** [comment]
Part of the reason is in the justification part of readme.md in pfn-nested folder. 

Also, since head to head and tail to tail are coming for different results, using the same feature might not be optimal. 
We learn that lesson from the previous works where people simply use the same feature for ner and re. 

Empirically speaking, switching them leads to faster convergence In our experiment. So we stick with this formula.

**Comment by debraj135** [comment]
Thank you for your prompt response. In terms of best performance, is there a significant difference between the two settings? And if yes, can you please elaborate?

**Comment by Coopercoppers** [comment]
Here is the thing, industry people used pfn on their Chinese dataset and the result is super low because there are so many head-overlap triples in their dataset. so I provided them with pfn-nested, the result got normal under pfn-nested.  All in all, pfn-nested is designed mainly to cover the issue of nested triple prediction. 

As for performance in current dataset, I only used it on scierc, the result is displayed in the main page though. I did try to use it on ace05, but I ran into oom error with batch size 20. 

There is no systematic evaluation of pfn-nested though, you can verify the performance yourself if you’re interested.

**Comment by debraj135** [comment]
Thank you. This answers my questions.

**Comment by debraj135** [comment]
And by the way, this work is indeed truly impressive. Best wishes on further explorations!

**Comment by Coopercoppers** [comment]
ok, thanks a lot.
